AdarshAddee/Hacktoberfest2022_for_Beginers

Python/print 1 to 100 without numbers.py

Create print 1 to 100 without numbers.py

---

CONTRIBUTORS.md
Javascript/print 1 to 100 without numbers.js

JavaScript Contribution . Let me know if any changes are needed

Print 1 to 100 without numbers in js

---

C/Star Pattern 1 in C.c
CONTRIBUTORS.md

Signed-off-by: Sarthak Roy <sarthakroy2002@gmail.com>

C: Add a * pattern

---

C/stack_arr.c

Stack implemented using integer array in C programming.

Stack implementation using array.

---

C++/Rock, Paper and Scissors Game By Suraj.cpp

It's Fun and Easy to Play and  Understand.

Created a Rock, Paper and Scissors Game using C++

---

C++/Heap sort by suraj.cpp

It's Easy and Fun to Understand.

Created Heap Sort Program

---

C++/Knapsack Problem by Suraj.cpp

It's Fun and Easy to Understand.

Created A Program of Knapsack Problem

---

C++/Tower of Hanoi By Suraj.cpp

It's Fun and Easy to Understand.

Created a Solution Finder for Tower fo Hanoi

---

C++/Binary Search By Suraj.cpp

It's Fun and Easy to Understand.

Created A Binary Search Program

---

C++/Dijkstra’s shortest path algorithm by Suraj.cpp

It's Fun and Easy to Understand.

Created a Dijsktra Algorithm Program

---

C++/kmp_algotihm.cpp

C++ program for implementation of KMP pattern searching algorithm

Created kmp_algotihm.cpp

---

C++/Transpose Of Matrix

I would like to contribute to the C++ repository.

Transpose Of Matrix

---

C++/Reverse_integer.cpp

added program for reverse integer.
please assign hactoberfest label.

reverse integer program

---

Python/webp to png.py

This code is created using pillow and os module in python. You have to provide the path to the images files you want to chagne.

Change image from webp to png

---

Python/Numberpattern.py

Added an number pattern in python

Added an number pattern

---

PHP/stringReverser.php

this is my mini app in php that reverse a string

added string reverser

---

C++/Search in Rotated Sorted Matrix

Please accept my pull request for Searchin in Rotated Sorted Matrix in c++;

Create Search in Rotated Sorted Matrix

---

CONTRIBUTORS.md
Dart/numbers.dart
README.md

Hello!!
Add folder for Dart language

number with Dart

---

CONTRIBUTORS.md
Java/InsertionSort.java

I added InsertionSort.java file
#Hacktoberfest2022

Added InsertionSort.java file

---

CONTRIBUTORS.md
Python/tic_tac_toe_game.py

Hello! I have coded console based Tic Tac Toe game in Python. It can be played between two players. :)
Here is a screenshot of game running -

Added Tic Tac Toe game in Python

---

Python/checkpass.py

Pwned Password Checker in Python

Checkpass.py

---

C/selection_sort.c

Selection Sort implementation in C language with explanation.

Selection_sort.c

---

Python/Steganography.py

A great tool to hide data in images

Steganography.py

---

C++/Merge_sort.cpp
CONTRIBUTORS.md

Hey there! Added Merge Sort Algorithm in cpp in cpp folder and updated contributors page as well! Happy Hacktoberfest!

Added Merge Sort Algorithm cpp

---

C++/factorialprogram.cpp

github navdeepk037
https://github.com/navdeepk037

created factorial program in cpp

---

C++/Counting_sort.cpp
CONTRIBUTORS.md

Update the CONTRIBUTORS.md and add the counting sort.cpp file
of Atinder kumar

Update the CONTRIBUTORS.md and add the counting sort.cpp file

---

C++/Connected_components.cpp

Number of connected components in an undirected graph

Created connected components cpp
